Refactor/web to webflux
ljusvita/projectD pull request #5
Opened 2022-05-08 04:06 UTC by ljusvita

# 내용 
- 그냥 스트링 통짜 반환하던거 리스트로 6문자 반환하게 수정

# 물어보고싶은거
이거 그냥 then 절에서 boolean 값이 false 가되면 테스트 실패하는건가?
뭔가 공식봐도 이런거에 대한 설명은 없어보이고 테스트 케이스 인터넷 올라온거보면 다들 지멋대로 쓰는거같은데 ㅋㅋㅋ
너같이 산토스 예제같이 쓴사람도 없음.. 파라미터라이즈 테스트라서 그런건지 몰라도

2022-05-08 04:51 UTC, flowertaekk-dev commented on lottery/src/test/groovy/com/example/lottery/app/Loto6ServiceTest.groovy
> +        actual.size() == expect.size()
여기서 false 가 나오면 실패 하는게 맞음!

2022-05-08 04:51 UTC, flowertaekk-dev commented on lottery/src/main/java/com/example/lottery/app/Loto6Service.java
> +    public List<String> pick() {
webflux 를 사용한다면 이렇게 가는게 맞음!
```suggestion
    public Flux<String> pick() {
```

2022-05-08 04:51 UTC, flowertaekk-dev commented on lottery/src/main/java/com/example/lottery/app/Loto6Controller.java
> +    public List<String> loto6() {
여기도 `Flux` !

2022-05-08 11:48 UTC, ljusvita commented on lottery/src/main/java/com/example/lottery/app/Loto6Service.java
> +    public List<String> pick() {
Flux : 0 ~ N 개의 데이터
Mono : 0 ~ 1 개의 데이터
군

2022-05-08 11:57 UTC, flowertaekk-dev commented on lottery/src/main/java/com/example/lottery/app/Loto6Service.java
> +    public List<String> pick() {
오늘 열심히 하넼ㅋㅋㅋㅋㅋLGTM!ㅋㅋㅋ

2022-05-21 10:58 UTC, flowertaekk-dev requested changes

2022-05-21 10:58 UTC, flowertaekk-dev commented on lottery/src/main/java/com/example/lottery/app/Loto7Controller.java
>  @RequestMapping("/loto7")
@ljusvita 
여기도 버전 붙이는 편이 좋을 듯!

2022-05-28 16:18 UTC, merged